# F1 Podium Predictor — Training

Binary XGBoost classifier for the probability a driver finishes on the podium (P≤3).
Thin orchestration: all logic lives in the tested `f1pred` package (see
`specs/003-ml-model`). Run top-to-bottom; it downloads FastF1 seasons (cached in
`.fastf1-cache/`), trains, evaluates against the grid-top-3 baseline, shows SHAP,
and uploads a versioned artifact + model card to S3.

Prereq: `pip install -e ".[dev,notebook]"` from `ml/`, plus AWS creds for the
upload step. FastF1's cold download is rate-limited (500 calls/h), so the first
run over a multi-season window may need to resume across hourly windows; cached
sessions are free on re-run.

In [1]:
# Run from the ml/ project root so the relative .fastf1-cache/ and artifacts/
# paths resolve the same way whether launched via nbconvert or from notebooks/.
import os
from pathlib import Path

if Path.cwd().name == "notebooks":
    os.chdir("..")
print("cwd:", Path.cwd())

cwd: /Users/martinschweiger/Developer/personal/F1-project/ml

In [2]:
import logging

import fastf1

from f1pred.data import fastf1_load_race, fastf1_rounds_for_year, load_seasons
from f1pred.pipeline import run_pipeline

logging.basicConfig(level=logging.INFO)
MODEL_VERSION = "0.1.0"
# Temporal split: train ≤ TRAIN_MAX_YEAR, validate on VAL_YEAR, test on TEST_YEAR.
# FIRST_YEAR bounds the FastF1 download window (cold pull is rate-limited to
# 500 calls/h, so we use a focused 2022–2025 window rather than 2018+).
FIRST_YEAR = 2022
TRAIN_MAX_YEAR, VAL_YEAR, TEST_YEAR = 2023, 2024, 2025

/Users/martinschweiger/Developer/personal/F1-project/ml/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Load historical races (FastF1)

First run downloads + caches; later runs are offline. Missing sessions are
skipped and logged (no silent imputation).

In [3]:
years = range(FIRST_YEAR, TEST_YEAR + 1)
races = load_seasons(
    years,
    rounds_for_year=fastf1_rounds_for_year,
    load_race=fastf1_load_race,
)
print(f"{len(races)} race-driver rows across {races['year'].nunique()} seasons")
races.head()

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 16 completed the race distance 00:00.050000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 16 completed the race distance 00:00.050000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '44', '63', '20', '77', '31', '22', '14', '24', '47', '18', '23', '3', '4', '6', '27', '11', '1', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '55', '44', '63', '20', '77', '31', '22', '14', '24', '47', '18', '23', '3', '4', '6', '27', '11', '1', '10']

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '55', '11', '44', '77', '20', '14', '63', '10', '31', '47', '4', '23', '24', '22', '27', '3', '18', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '1', '55', '11', '44', '77', '20', '14', '63', '10', '31', '47', '4', '23', '24', '22', '27', '3', '18', '6']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	No lap data for driver 22

WARNING:fastf1.fastf1.core:No lap data for driver 22

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 47)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 47)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '31', '4', '10', '20', '44', '24', '27', '18', '23', '77', '14', '3', '6', '22', '47']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '31', '4', '10', '20', '44', '24', '27', '18', '23', '77', '14', '3', '6', '22', '47']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['11', '16', '55', '1', '31', '63', '14', '77', '10', '20', '4', '3', '24', '47', '18', '44', '23', '27', '6', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['11', '16', '55', '1', '31', '63', '14', '77', '10', '20', '4', '3', '24', '47', '18', '44', '23', '27', '6', '22']

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 16 completed the race distance 00:00.140000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 16 completed the race distance 00:00.140000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['16', '11', '63', '44', '4', '3', '31', '77', '10', '23', '24', '18', '47', '20', '22', '6', '14', '1', '5', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '11', '63', '44', '4', '3', '31', '77', '10', '23', '24', '18', '47', '20', '22', '6', '14', '1', '5', '55']

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '11', '4', '44', '63', '3', '31', '55', '14', '10', '77', '22', '24', '47', '23', '20', '5', '6', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '1', '11', '4', '44', '63', '3', '31', '55', '14', '10', '77', '22', '24', '47', '23', '20', '5', '6', '18']

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '63', '77', '16', '22', '5', '20', '18', '23', '10', '44', '31', '24', '6', '47', '3', '14', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '4', '63', '77', '16', '22', '5', '20', '18', '23', '10', '44', '31', '24', '6', '47', '3', '14', '55']

core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '4', '20', '14', '3', '11', '77', '5', '55', '63', '47', '44', '24', '18', '22', '10', '6', '31', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '4', '20', '14', '3', '11', '77', '5', '55', '63', '47', '44', '24', '18', '22', '10', '6', '31', '23']

core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '44', '77', '31', '23', '18', '14', '22', '3', '6', '47', '20', '5', '10', '4', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '55', '11', '63', '44', '77', '31', '23', '18', '14', '22', '3', '6', '47', '20', '5', '10', '4', '24']

core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	No lap data for driver 31

WARNING:fastf1.fastf1.core:No lap data for driver 31

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 31)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 31)

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '11', '77', '44', '10', '4', '22', '18', '14', '63', '5', '3', '47', '20', '24', '23', '6', '31']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '55', '1', '11', '77', '44', '10', '4', '22', '18', '14', '63', '5', '3', '47', '20', '24', '23', '6', '31']

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '55', '44', '77', '31', '4', '14', '22', '5', '3', '10', '47', '18', '6', '20', '23', '24', '16']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '63', '55', '44', '77', '31', '4', '14', '22', '5', '3', '10', '47', '18', '6', '20', '23', '24', '16']

core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '55', '63', '11', '44', '77', '20', '3', '47', '4', '31', '22', '10', '24', '5', '14', '18', '23', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '1', '55', '63', '11', '44', '77', '20', '3', '47', '4', '31', '22', '10', '24', '5', '14', '18', '23', '6']

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '11'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '11'

core        WARNING 	Fixed incorrect tyre stint information for driver '55'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '55'

core        WARNING 	Fixed incorrect tyre stint information for driver '1'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '1'

core        WARNING 	Fixed incorrect tyre stint information for driver '16'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '16'

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '63'

core        WARNING 	Fixed incorrect tyre stint information for driver '4'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '4'

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '44'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '44'

core        WARNING 	Fixed incorrect tyre stint information for driver '77'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '77'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '31'

core        WARNING 	Fixed incorrect tyre stint information for driver '3'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '3'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '6'

core        WARNING 	Fixed incorrect tyre stint information for driver '24'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '24'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '22'

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '47'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '47'

core        WARNING 	Fixed incorrect tyre stint information for driver '20'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '20'

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['11', '55', '1', '16', '63', '4', '14', '44', '77', '5', '10', '31', '3', '18', '6', '24', '22', '23', '47', '20']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['11', '55', '1', '16', '63', '4', '14', '44', '77', '5', '10', '31', '3', '18', '6', '24', '22', '23', '47', '20']

core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '11', '1', '4', '63', '14', '44', '5', '31', '22', '77', '20', '3', '47', '23', '10', '18', '6', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '55', '11', '1', '4', '63', '14', '44', '5', '31', '22', '77', '20', '3', '47', '23', '10', '18', '6', '24']

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '63', '44', '10', '5', '14', '3', '4', '31', '77', '23', '22', '47', '6', '18', '20', '24', '16', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '63', '44', '10', '5', '14', '3', '4', '31', '77', '23', '22', '47', '6', '18', '20', '24', '16', '55']

core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '11', '1', '55', '63', '10', '44', '22', '5', '14', '4', '3', '31', '24', '77', '20', '23', '6', '18', '47']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '11', '1', '55', '63', '10', '44', '22', '5', '14', '4', '3', '31', '24', '77', '20', '23', '6', '18', '47']

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '55', '44', '63', '16', '31', '77', '24', '14', '18', '3', '5', '23', '10', '4', '6', '20', '22', '47', '11']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '55', '44', '63', '16', '31', '77', '24', '14', '18', '3', '5', '23', '10', '4', '6', '20', '22', '47', '11']

core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '55', '44', '20', '47', '31', '63', '3', '24', '77', '23', '11', '4', '16', '10', '5', '18', '6', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '14', '55', '44', '20', '47', '31', '63', '3', '24', '77', '23', '11', '4', '16', '10', '5', '18', '6', '22']

core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['55', '11', '44', '16', '14', '4', '1', '47', '5', '20', '18', '6', '3', '22', '31', '10', '77', '63', '24', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '11', '44', '16', '14', '4', '1', '47', '5', '20', '18', '6', '3', '22', '31', '10', '77', '63', '24', '23']

core           INFO 	Loading data for British Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['55', '1', '16', '11', '44', '4', '14', '63', '24', '6', '10', '77', '22', '3', '31', '23', '20', '5', '47', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '1', '16', '11', '44', '4', '14', '63', '24', '6', '10', '77', '22', '3', '31', '23', '20', '5', '47', '18']

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '16'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '16'

core        WARNING 	Fixed incorrect tyre stint information for driver '1'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '1'

core        WARNING 	Fixed incorrect tyre stint information for driver '44'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '44'

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '63'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '31'

core        WARNING 	Fixed incorrect tyre stint information for driver '47'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '47'

core        WARNING 	Fixed incorrect tyre stint information for driver '4'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '4'

core        WARNING 	Fixed incorrect tyre stint information for driver '20'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '20'

core        WARNING 	Fixed incorrect tyre stint information for driver '3'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '3'

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '77'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '77'

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '24'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '24'

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '22'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Fixed incorrect tyre stint information for driver '55'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '55'

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '6'

core        WARNING 	Fixed incorrect tyre stint information for driver '11'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '11'

core        WARNING 	Driver 16 completed the race distance 00:00.024000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 16 completed the race distance 00:00.024000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '44', '63', '31', '47', '4', '20', '3', '14', '77', '23', '18', '24', '10', '22', '5', '55', '6', '11']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '1', '44', '63', '31', '47', '4', '20', '3', '14', '77', '23', '18', '24', '10', '22', '5', '55', '6', '11']

core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '63', '31', '20', '47', '14', '44', '10', '23', '77', '11', '22', '4', '3', '18', '24', '6', '5']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '55', '63', '31', '20', '47', '14', '44', '10', '23', '77', '11', '22', '4', '3', '18', '24', '6', '5']

core           INFO 	Loading data for French Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for French Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:00.041000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:00.041000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '14', '4', '31', '3', '18', '5', '10', '23', '77', '47', '24', '6', '20', '16', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '14', '4', '31', '3', '18', '5', '10', '23', '77', '47', '24', '6', '20', '16', '22']

core           INFO 	Loading data for French Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for French Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '11', '44', '4', '63', '14', '22', '55', '20', '3', '31', '77', '5', '23', '10', '18', '24', '47', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '1', '11', '44', '4', '63', '14', '22', '55', '20', '3', '31', '77', '5', '23', '10', '18', '24', '47', '6']

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '55', '11', '16', '4', '14', '31', '5', '18', '10', '24', '47', '3', '20', '23', '6', '22', '77']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '44', '63', '55', '11', '16', '4', '14', '31', '5', '18', '10', '24', '47', '3', '20', '23', '6', '22', '77']

core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['63', '55', '16', '4', '31', '14', '44', '77', '3', '1', '11', '24', '20', '18', '47', '22', '23', '5', '10', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '55', '16', '4', '31', '14', '44', '77', '3', '1', '11', '24', '20', '18', '47', '22', '23', '5', '10', '6']

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '22'

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '63', '14', '16', '31', '5', '10', '23', '18', '4', '22', '24', '3', '20', '47', '6', '77', '44']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '55', '63', '14', '16', '31', '5', '10', '23', '18', '4', '22', '24', '3', '20', '47', '6', '77', '44']

core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '55', '11', '16', '31', '14', '44', '63', '23', '4', '3', '10', '24', '18', '47', '5', '6', '20', '22', '77']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '55', '11', '16', '31', '14', '44', '63', '23', '4', '3', '10', '24', '18', '47', '5', '6', '20', '22', '77']

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '16', '44', '11', '14', '4', '55', '31', '18', '10', '23', '47', '5', '20', '24', '3', '6', '77', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '63', '16', '44', '11', '14', '4', '55', '31', '18', '10', '23', '47', '5', '20', '24', '3', '6', '77', '22']

core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '44', '11', '63', '4', '47', '22', '18', '10', '31', '14', '24', '23', '77', '3', '20', '5', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '55', '44', '11', '63', '4', '47', '22', '18', '10', '31', '14', '24', '23', '77', '3', '20', '5', '6']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '44', '11', '4', '10', '45', '24', '31', '47', '77', '22', '6', '20', '3', '18', '14', '5']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '63', '55', '44', '11', '4', '10', '45', '24', '31', '47', '77', '22', '6', '20', '3', '18', '14', '5']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '55', '11', '44', '63', '4', '3', '10', '14', '31', '77', '45', '24', '22', '6', '5', '18', '20', '47']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '1', '55', '11', '44', '63', '4', '3', '10', '14', '31', '77', '45', '24', '22', '6', '5', '18', '20', '47']

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['11', '16', '55', '4', '3', '18', '1', '5', '44', '10', '77', '20', '47', '63', '22', '31', '23', '14', '6', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['11', '16', '55', '4', '3', '18', '1', '5', '44', '10', '77', '20', '47', '63', '22', '31', '23', '14', '6', '24']

core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '11', '44', '55', '14', '4', '10', '1', '20', '22', '63', '18', '47', '5', '24', '77', '3', '31', '23', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '11', '44', '55', '14', '4', '10', '1', '20', '22', '63', '18', '47', '5', '24', '77', '3', '31', '23', '6']

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '31', '44', '5', '14', '63', '6', '4', '3', '18', '22', '20', '77', '24', '47', '10', '55', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '16', '31', '44', '5', '14', '63', '6', '4', '3', '18', '22', '20', '77', '24', '47', '10', '55', '23']

core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '31', '44', '14', '63', '5', '4', '3', '77', '22', '24', '47', '23', '10', '20', '18', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '55', '11', '31', '44', '14', '63', '5', '4', '3', '77', '22', '24', '47', '23', '10', '20', '18', '6']

core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '11', '63', '4', '14', '5', '20', '22', '31', '24', '23', '10', '47', '3', '6', '18', '77', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '44', '16', '11', '63', '4', '14', '5', '20', '22', '31', '24', '23', '10', '47', '3', '6', '18', '77', '55']

core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['55', '16', '1', '11', '44', '63', '18', '4', '14', '77', '23', '5', '10', '24', '22', '20', '3', '31', '47', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '16', '1', '11', '44', '63', '18', '4', '14', '77', '23', '5', '10', '24', '22', '20', '3', '31', '47', '6']

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '11', '63', '55', '16', '3', '31', '4', '77', '10', '23', '24', '5', '18', '47', '20', '6', '14', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '44', '11', '63', '55', '16', '3', '31', '4', '77', '10', '23', '24', '5', '18', '47', '20', '6', '14', '22']

core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '44', '11', '55', '77', '16', '4', '14', '31', '3', '24', '22', '10', '20', '47', '5', '18', '23', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '63', '44', '11', '55', '77', '16', '4', '14', '31', '3', '24', '22', '10', '20', '47', '5', '18', '23', '6']

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '14', '1', '11', '31', '77', '18', '5', '24', '47', '10', '23', '6', '22', '4', '20', '3']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '44', '55', '16', '14', '1', '11', '31', '77', '18', '5', '24', '47', '10', '23', '6', '22', '4', '20', '3']

core           INFO 	Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['20', '1', '63', '4', '55', '31', '14', '44', '11', '16', '23', '10', '5', '3', '18', '6', '24', '77', '22', '47']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['20', '1', '63', '4', '55', '31', '14', '44', '11', '16', '23', '10', '5', '3', '18', '6', '24', '77', '22', '47']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '55', '63', '4', '31', '18', '3', '5', '22', '24', '23', '10', '77', '47', '20', '44', '6', '14']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '11', '55', '63', '4', '31', '18', '3', '5', '22', '24', '23', '10', '77', '47', '20', '44', '6', '14']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '55', '44', '63', '4', '31', '5', '3', '14', '22', '47', '18', '24', '20', '10', '77', '23', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '16', '55', '44', '63', '4', '31', '5', '3', '14', '22', '47', '18', '24', '20', '10', '77', '23', '6']

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '55', '14', '63', '44', '18', '31', '27', '4', '77', '24', '22', '23', '2', '20', '81', '21', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '16', '55', '14', '63', '44', '18', '31', '27', '4', '77', '24', '22', '23', '2', '20', '81', '21', '10']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 11 completed the race distance 00:00.035000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 11 completed the race distance 00:00.035000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['11', '16', '14', '63', '55', '18', '31', '44', '81', '10', '27', '24', '20', '77', '1', '22', '23', '21', '4', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['11', '16', '14', '63', '55', '18', '31', '44', '81', '10', '27', '24', '20', '77', '1', '22', '23', '21', '4', '2']

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '44', '14', '55', '18', '16', '23', '10', '27', '31', '22', '4', '20', '21', '81', '24', '2', '77', '11']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '63', '44', '14', '55', '18', '16', '23', '10', '27', '31', '22', '4', '20', '21', '81', '24', '2', '77', '11']

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['11', '1', '16', '14', '55', '44', '18', '63', '4', '22', '81', '23', '20', '10', '31', '2', '27', '77', '24', '21']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['11', '1', '16', '14', '55', '44', '18', '63', '4', '22', '81', '23', '20', '10', '31', '2', '27', '77', '24', '21']

core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '11', '55', '44', '14', '4', '22', '18', '81', '63', '31', '23', '77', '2', '24', '27', '20', '10', '21']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '1', '11', '55', '44', '14', '4', '22', '18', '81', '63', '31', '23', '77', '2', '24', '27', '20', '10', '21']

core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']

core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['11', '14', '55', '20', '10', '63', '16', '31', '1', '77', '23', '27', '44', '24', '21', '4', '22', '18', '81', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['11', '14', '55', '20', '10', '63', '16', '31', '1', '77', '23', '27', '44', '24', '21', '4', '22', '18', '81', '2']

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']

core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '16', '31', '55', '44', '10', '63', '22', '4', '81', '21', '23', '18', '77', '2', '20', '27', '24', '11']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '14', '16', '31', '55', '44', '10', '63', '22', '4', '81', '21', '23', '18', '77', '2', '20', '27', '24', '11']

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:00.037000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:00.037000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']

core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '55', '4', '10', '44', '18', '31', '27', '14', '81', '11', '63', '24', '21', '22', '77', '20', '23', '16', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '55', '4', '10', '44', '18', '31', '27', '14', '81', '11', '63', '24', '21', '22', '77', '20', '23', '16', '2']

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '22'

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']

core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '27', '14', '44', '63', '31', '4', '55', '81', '23', '16', '11', '18', '20', '77', '22', '10', '21', '2', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '27', '14', '44', '63', '31', '4', '55', '81', '23', '16', '11', '18', '20', '77', '22', '10', '21', '2', '24']

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '4', '14', '55', '63', '44', '18', '10', '23', '24', '2', '31', '77', '81', '21', '20', '22', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '11', '4', '14', '55', '63', '44', '18', '10', '23', '24', '2', '31', '77', '81', '21', '20', '22', '27']

core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '4', '44', '18', '14', '27', '10', '23', '63', '31', '81', '77', '11', '22', '24', '2', '20', '21']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '55', '4', '44', '18', '14', '27', '10', '23', '63', '31', '81', '77', '11', '22', '24', '2', '20', '21']

core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']

core           INFO 	Loading data for British Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '55', '63', '44', '23', '14', '10', '27', '18', '31', '2', '77', '11', '22', '24', '21', '20']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '16', '55', '63', '44', '23', '14', '10', '27', '18', '31', '2', '77', '11', '22', '24', '21', '20']

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']

core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '63'

core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '24', '16', '77', '14', '11', '27', '55', '31', '3', '18', '10', '23', '22', '63', '20', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['44', '1', '4', '81', '24', '16', '77', '14', '11', '27', '55', '31', '3', '18', '10', '23', '22', '63', '20', '2']

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '44', '14', '63', '4', '31', '18', '22', '10', '77', '24', '23', '20', '3', '2', '27', '55', '81']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '16', '44', '14', '63', '4', '31', '18', '22', '10', '77', '24', '23', '20', '3', '2', '27', '55', '81']

core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '44', '55', '81', '4', '63', '14', '18', '22', '10', '20', '77', '31', '23', '24', '2', '3', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '11', '44', '55', '81', '4', '63', '14', '18', '22', '10', '20', '77', '31', '23', '24', '2', '3', '27']

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:02.059000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:02.059000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '14', '10', '11', '55', '44', '4', '23', '81', '31', '18', '27', '40', '77', '22', '20', '63', '24', '16', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '14', '10', '11', '55', '44', '4', '23', '81', '31', '18', '27', '40', '77', '22', '20', '63', '24', '16', '2']

core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '23', '14', '55', '11', '81', '16', '2', '18', '10', '44', '22', '27', '24', '31', '20', '77', '40']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '63', '23', '14', '55', '11', '81', '16', '2', '18', '10', '44', '22', '27', '24', '31', '20', '77', '40']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)

core        WARNING 	Driver 1 completed the race distance 06:25.888000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 06:25.888000 before the recorded end of the session.

core        WARNING 	Driver 11 completed the race distance 06:19.824000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 11 completed the race distance 06:19.824000 before the recorded end of the session.

core        WARNING 	Driver 55 completed the race distance 06:14.695000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 55 completed the race distance 06:14.695000 before the recorded end of the session.

core        WARNING 	Driver 16 completed the race distance 06:14.511000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 16 completed the race distance 06:14.511000 before the recorded end of the session.

core        WARNING 	Driver 63 completed the race distance 06:07.860000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 63 completed the race distance 06:07.860000 before the recorded end of the session.

core        WARNING 	Driver 44 completed the race distance 05:48.209000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 44 completed the race distance 05:48.209000 before the recorded end of the session.

core        WARNING 	Driver 23 completed the race distance 05:40.782000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 23 completed the race distance 05:40.782000 before the recorded end of the session.

core        WARNING 	Driver 4 completed the race distance 05:40.439000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 4 completed the race distance 05:40.439000 before the recorded end of the session.

core        WARNING 	Driver 14 completed the race distance 05:39.594000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 14 completed the race distance 05:39.594000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['55', '1', '16', '63', '11', '23', '81', '44', '4', '14', '22', '40', '27', '77', '2', '24', '10', '31', '20', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '1', '16', '63', '11', '23', '81', '44', '4', '14', '22', '40', '27', '77', '2', '24', '10', '31', '20', '18']

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['55', '4', '44', '16', '1', '10', '81', '11', '40', '20', '23', '24', '27', '2', '14', '63', '77', '31', '22', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '4', '44', '16', '1', '10', '81', '11', '40', '20', '23', '24', '27', '2', '14', '63', '77', '31', '22', '18']

core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['55', '63', '16', '4', '44', '20', '14', '31', '27', '40', '1', '10', '11', '23', '22', '77', '81', '2', '24', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '63', '16', '4', '44', '20', '14', '31', '27', '40', '1', '10', '11', '23', '22', '77', '81', '2', '24', '18']

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:00.076000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:00.076000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '55', '63', '14', '31', '10', '40', '22', '24', '27', '20', '23', '2', '18', '11', '77']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '55', '63', '14', '31', '10', '40', '22', '24', '27', '20', '23', '2', '18', '11', '77']

core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '11', '55', '44', '63', '22', '14', '40', '10', '23', '31', '20', '77', '18', '27', '24', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '81', '4', '16', '11', '55', '44', '63', '22', '14', '40', '10', '23', '31', '20', '77', '18', '27', '24', '2']

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Qatar Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '16', '14', '31', '77', '24', '11', '18', '10', '23', '20', '22', '27', '40', '2', '44', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '81', '4', '63', '16', '14', '31', '77', '24', '11', '18', '10', '23', '20', '22', '27', '40', '2', '44', '55']

core           INFO 	Loading data for Qatar Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Qatar Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '44', '14', '16', '81', '10', '31', '77', '4', '22', '55', '11', '23', '27', '2', '18', '40', '20', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '63', '44', '14', '16', '81', '10', '31', '77', '4', '22', '55', '11', '23', '27', '2', '18', '40', '20', '24']

core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '55', '11', '63', '10', '18', '22', '23', '2', '27', '77', '24', '20', '3', '14', '81', '31', '44', '16']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '55', '11', '63', '10', '18', '22', '23', '2', '27', '77', '24', '20', '3', '14', '81', '31', '44', '16']

core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '4', '44', '55', '63', '1', '10', '31', '11', '81', '22', '24', '77', '20', '3', '27', '14', '23', '18', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '4', '44', '55', '63', '1', '10', '31', '11', '81', '22', '24', '77', '20', '3', '27', '14', '23', '18', '2']

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '55', '4', '63', '3', '81', '23', '31', '10', '22', '27', '24', '77', '2', '18', '14', '20', '11']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '44', '16', '55', '4', '63', '3', '81', '23', '31', '10', '22', '27', '24', '77', '2', '18', '14', '20', '11']

core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '3', '11', '44', '81', '63', '77', '24', '10', '27', '14', '23', '22', '31', '20', '18', '4', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '55', '1', '3', '11', '44', '81', '63', '77', '24', '10', '27', '14', '23', '22', '31', '20', '18', '4', '2']

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 16)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 16)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '14', '11', '18', '55', '10', '44', '22', '31', '2', '27', '3', '81', '63', '77', '24', '20', '23', '16']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '14', '11', '18', '55', '10', '44', '22', '31', '2', '27', '3', '81', '63', '77', '24', '20', '23', '16']

core           INFO 	Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '18', '14', '44', '63', '4', '55', '11', '81', '27', '31', '10', '20', '23', '22', '3', '77', '2', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '18', '14', '44', '63', '4', '55', '11', '81', '27', '31', '10', '20', '23', '22', '3', '77', '2', '24']

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Las Vegas Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:00.001000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:00.001000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '31', '18', '55', '44', '63', '14', '81', '10', '23', '20', '3', '24', '2', '77', '22', '27', '4']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '11', '31', '18', '55', '44', '63', '14', '81', '10', '23', '20', '3', '24', '2', '77', '22', '27', '4']

core           INFO 	Loading data for Las Vegas Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Las Vegas Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '63', '10', '23', '2', '77', '20', '14', '44', '11', '27', '18', '3', '4', '31', '24', '81', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '55', '1', '63', '10', '23', '2', '77', '20', '14', '44', '11', '27', '18', '3', '4', '31', '24', '81', '22']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '11', '4', '81', '14', '22', '44', '18', '3', '31', '10', '23', '27', '2', '24', '55', '77', '20']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '63', '11', '4', '81', '14', '22', '44', '18', '3', '31', '10', '23', '27', '2', '24', '55', '77', '20']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '4', '22', '14', '27', '11', '10', '44', '31', '18', '23', '3', '55', '20', '77', '24', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '81', '63', '4', '22', '14', '27', '11', '10', '44', '31', '18', '23', '3', '55', '20', '77', '24', '2']

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '11', '14', '4', '81', '44', '27', '22', '18', '23', '3', '20', '77', '24', '2', '31', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '63', '55', '11', '14', '4', '81', '44', '27', '22', '18', '23', '3', '20', '77', '24', '2', '31', '10']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '14', '81', '4', '63', '44', '22', '18', '38', '23', '20', '3', '27', '77', '31', '10', '2', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '11', '14', '81', '4', '63', '44', '22', '18', '38', '23', '20', '3', '27', '77', '31', '10', '2', '24']

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']

INFO:fastf1.fastf1.core:Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 19 drivers: ['1', '55', '11', '4', '16', '81', '63', '22', '18', '14', '44', '23', '77', '20', '31', '27', '10', '3', '24']

INFO:fastf1.fastf1.core:Finished loading data for 19 drivers: ['1', '55', '11', '4', '16', '81', '63', '22', '18', '14', '44', '23', '77', '20', '31', '27', '10', '3', '24']

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']

core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '4', '55', '14', '81', '44', '16', '63', '22', '3', '27', '77', '23', '31', '18', '10', '20', '2', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '4', '55', '14', '81', '44', '16', '63', '22', '3', '27', '77', '23', '31', '18', '10', '20', '2', '24']

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Chinese Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']

core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Chinese Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '4', '81', '16', '55', '63', '27', '77', '18', '3', '31', '23', '10', '24', '20', '44', '22', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '11', '14', '4', '81', '16', '55', '63', '27', '77', '18', '3', '31', '23', '10', '24', '20', '44', '22', '2']

core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']

core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '55', '11', '4', '81', '63', '44', '27', '22', '18', '10', '31', '23', '14', '77', '2', '3', '20', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '55', '11', '4', '81', '63', '44', '27', '22', '18', '10', '31', '23', '14', '77', '2', '3', '20', '24']

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']

core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '55', '63', '22', '44', '3', '27', '11', '31', '18', '23', '10', '77', '24', '20', '14', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '81', '4', '16', '55', '63', '22', '44', '3', '27', '11', '31', '18', '23', '10', '77', '24', '20', '14', '2']

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']

core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '31', '3', '18', '27', '14', '2', '20', '11', '77', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '31', '3', '18', '27', '14', '2', '20', '11', '77', '24']

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']

core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '3', '14', '44', '22', '18', '23', '16', '55', '2', '20', '10', '11', '77', '31', '27', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '1', '4', '81', '3', '14', '44', '22', '18', '23', '16', '55', '2', '20', '10', '11', '77', '31', '27', '24']

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']

core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '44', '63', '16', '55', '10', '11', '31', '81', '14', '77', '27', '18', '24', '20', '22', '3', '23', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '44', '63', '16', '55', '10', '11', '31', '81', '14', '77', '27', '18', '24', '20', '22', '3', '23', '2']

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['63', '81', '55', '44', '1', '27', '11', '20', '3', '10', '16', '31', '18', '22', '23', '77', '24', '14', '2', '4']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '81', '55', '44', '1', '27', '11', '20', '3', '10', '16', '31', '18', '22', '23', '77', '24', '14', '2', '4']

core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '55', '44', '16', '81', '11', '27', '31', '3', '20', '10', '22', '14', '23', '18', '77', '2', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '63', '55', '44', '16', '81', '11', '27', '31', '3', '20', '10', '22', '14', '23', '18', '77', '2', '24']

core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 10)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 10)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']

core           INFO 	Loading data for British Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '18'

core           INFO 	Finished loading data for 20 drivers: ['63', '44', '4', '1', '81', '27', '55', '18', '23', '14', '16', '2', '22', '24', '3', '77', '20', '31', '11', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '44', '4', '1', '81', '27', '55', '18', '23', '14', '16', '2', '22', '24', '3', '77', '20', '31', '11', '10']

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '44', '16', '1', '55', '11', '63', '22', '18', '14', '3', '27', '23', '20', '77', '2', '31', '24', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '4', '44', '16', '1', '55', '11', '63', '22', '18', '14', '3', '27', '23', '20', '77', '2', '31', '24', '10']

core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '55', '44', '16', '14', '18', '3', '22', '27', '77', '23', '2', '20', '11', '63', '24', '31', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '1', '55', '44', '16', '14', '18', '3', '22', '27', '77', '23', '2', '20', '11', '63', '24', '31', '10']

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '3'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '3'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '22'

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['44', '81', '16', '1', '4', '55', '11', '14', '31', '3', '18', '23', '10', '20', '77', '22', '2', '27', '24', '63']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['44', '81', '16', '1', '4', '55', '11', '14', '31', '3', '18', '23', '10', '20', '77', '22', '2', '27', '24', '63']

core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '44', '4', '81', '63', '55', '14', '31', '23', '10', '3', '77', '18', '27', '20', '22', '2', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '11', '44', '4', '81', '63', '55', '14', '31', '23', '10', '3', '77', '18', '27', '20', '22', '2', '24']

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '81', '55', '11', '63', '44', '10', '14', '27', '3', '18', '23', '31', '2', '22', '20', '77', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '16', '81', '55', '11', '63', '44', '10', '14', '27', '3', '18', '23', '31', '2', '22', '20', '77', '24']

core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	No lap data for driver 2

WARNING:fastf1.fastf1.core:No lap data for driver 2

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 2)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 2)

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '11', '16', '14', '18', '10', '55', '23', '44', '22', '27', '20', '3', '31', '77', '24', '2']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '81', '63', '11', '16', '14', '18', '10', '55', '23', '44', '22', '27', '20', '3', '31', '77', '24', '2']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '55', '44', '1', '11', '23', '27', '14', '3', '20', '10', '31', '22', '18', '43', '77', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '63', '16', '55', '44', '1', '11', '23', '27', '14', '3', '20', '10', '31', '22', '18', '43', '77', '24']

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '16', '63', '4', '1', '14', '23', '43', '44', '50', '27', '10', '3', '24', '31', '77', '11', '55', '18', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '16', '63', '4', '1', '14', '23', '43', '44', '50', '27', '10', '3', '24', '31', '77', '11', '55', '18', '22']

core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '11', '63', '1', '44', '14', '43', '23', '50', '22', '27', '18', '3', '10', '4', '77', '24', '31']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '81', '55', '11', '63', '1', '44', '14', '43', '23', '50', '22', '27', '18', '3', '10', '4', '77', '24', '31']

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']

core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '44', '63', '81', '27', '14', '22', '16', '55', '23', '43', '11', '20', '31', '3', '18', '10', '77', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '44', '63', '81', '27', '14', '22', '16', '55', '23', '43', '11', '20', '31', '3', '18', '10', '77', '24']

core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '4', '81', '63', '11', '27', '30', '43', '20', '10', '14', '22', '18', '23', '77', '31', '24', '44']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '55', '1', '4', '81', '63', '11', '27', '30', '43', '20', '10', '14', '22', '18', '23', '77', '31', '24', '44']

core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '55', '16', '81', '63', '10', '14', '20', '11', '22', '27', '31', '18', '30', '23', '43', '77', '44', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '55', '16', '81', '63', '10', '14', '20', '11', '22', '27', '31', '18', '30', '23', '43', '77', '44', '24']

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['55', '4', '16', '44', '63', '1', '20', '81', '27', '10', '18', '43', '31', '77', '24', '30', '11', '14', '23', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '4', '16', '44', '63', '1', '20', '81', '27', '10', '18', '43', '31', '77', '24', '30', '11', '14', '23', '22']

core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['55', '1', '4', '16', '63', '44', '20', '10', '23', '27', '22', '30', '14', '18', '77', '43', '81', '11', '31', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['55', '1', '4', '16', '63', '44', '20', '10', '23', '27', '22', '30', '14', '18', '77', '43', '81', '11', '31', '24']

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '31', '10', '63', '16', '4', '22', '81', '30', '44', '11', '50', '77', '14', '24', '55', '43', '23', '18', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '31', '10', '63', '16', '4', '22', '81', '30', '44', '11', '50', '77', '14', '24', '55', '43', '23', '18', '27']

core           INFO 	Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '55'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '55'

core           INFO 	Finished loading data for 20 drivers: ['4', '63', '22', '31', '30', '16', '23', '81', '14', '18', '77', '1', '11', '55', '10', '44', '50', '43', '27', '24']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '63', '22', '31', '30', '16', '23', '81', '14', '18', '77', '1', '11', '55', '10', '44', '50', '43', '27', '24']

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Las Vegas Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 63: Lap timing integrity check failed for 2 lap(s)

WARNING:fastf1.fastf1.core:Driver 63: Lap timing integrity check failed for 2 lap(s)

core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)

WARNING:fastf1.fastf1.core:Driver 44: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 55: Lap timing integrity check failed for 1 lap(s)

WARNING:fastf1.fastf1.core:Driver 55: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 16: Lap timing integrity check failed for 2 lap(s)

WARNING:fastf1.fastf1.core:Driver 16: Lap timing integrity check failed for 2 lap(s)

core        WARNING 	Driver  1: Lap timing integrity check failed for 1 lap(s)

WARNING:fastf1.fastf1.core:Driver  1: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver  4: Lap timing integrity check failed for 1 lap(s)

WARNING:fastf1.fastf1.core:Driver  4: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 81: Lap timing integrity check failed for 1 lap(s)

WARNING:fastf1.fastf1.core:Driver 81: Lap timing integrity check failed for 1 lap(s)

core        WARNING 	Driver 30: Lap timing integrity check failed for 2 lap(s)

WARNING:fastf1.fastf1.core:Driver 30: Lap timing integrity check failed for 2 lap(s)

core        WARNING 	Driver 77: Lap timing integrity check failed for 2 lap(s)

WARNING:fastf1.fastf1.core:Driver 77: Lap timing integrity check failed for 2 lap(s)

core        WARNING 	Driver 63 completed the race distance 00:00.427000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 63 completed the race distance 00:00.427000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']

core           INFO 	Loading data for Las Vegas Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Las Vegas Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['63', '55', '10', '16', '1', '4', '22', '81', '27', '44', '31', '20', '24', '43', '30', '11', '14', '23', '77', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '55', '10', '16', '1', '4', '22', '81', '27', '44', '31', '20', '24', '43', '30', '11', '14', '23', '77', '18']

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Qatar Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '43'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '43'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '31'

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '10', '55', '14', '24', '20', '4', '77', '44', '22', '30', '23', '27', '11', '18', '43', '31']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '16', '81', '63', '10', '55', '14', '24', '20', '4', '77', '44', '22', '30', '23', '27', '11', '18', '43', '31']

core           INFO 	Loading data for Qatar Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Qatar Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '4', '81', '16', '44', '55', '14', '11', '20', '10', '24', '77', '22', '18', '23', '30', '27', '43', '31']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '63', '4', '81', '16', '44', '55', '14', '11', '20', '10', '24', '77', '22', '18', '23', '30', '27', '43', '31']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '55', '27', '1', '10', '63', '14', '77', '11', '22', '30', '18', '16', '20', '23', '24', '44', '43', '61']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '55', '27', '1', '10', '63', '14', '77', '11', '22', '30', '18', '16', '20', '23', '24', '44', '43', '61']

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '87'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '87'

core        WARNING 	Fixed incorrect tyre stint information for driver '30'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '30'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Australian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '4'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '4'

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Chinese Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '4', '63', '1', '31', '12', '23', '87', '18', '55', '6', '30', '7', '5', '27', '22', '14', '16', '44', '10']

core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Chinese Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '1', '44', '16', '6', '12', '22', '23', '31', '27', '14', '18', '55', '10', '87', '7', '5', '30']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '63', '4', '1', '44', '16', '6', '12', '22', '23', '31', '27', '14', '18', '55', '10', '87', '7', '5', '30']

core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '44', '6', '23', '87', '14', '22', '10', '55', '7', '27', '30', '31', '5', '18']

core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '6', '44', '23', '87', '10', '55', '14', '30', '22', '27', '5', '31', '7', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '6', '44', '23', '87', '10', '55', '14', '30', '22', '27', '5', '31', '7', '18']

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '63', '4', '16', '44', '1', '10', '31', '22', '87', '12', '23', '6', '7', '14', '30', '18', '5', '55', '27']

core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Bahrain Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['81', '63', '16', '12', '10', '4', '1', '55', '44', '22', '7', '6', '14', '31', '23', '27', '30', '5', '18', '87']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '63', '16', '12', '10', '4', '1', '55', '44', '22', '7', '6', '14', '31', '23', '27', '30', '5', '18', '87']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '1', '16', '4', '63', '12', '44', '55', '23', '6', '14', '30', '87', '31', '27', '18', '7', '5', '22', '10']

core           INFO 	Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Saudi Arabian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '5'

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '63', '16', '12', '55', '44', '22', '10', '4', '23', '30', '14', '6', '87', '18', '7', '27', '31', '5']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '81', '63', '16', '12', '55', '44', '22', '10', '4', '23', '30', '14', '6', '87', '18', '7', '27', '31', '5']

core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 81 completed the race distance 00:00.036000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '4', '63', '1', '23', '12', '16', '44', '55', '22', '6', '31', '10', '27', '14', '18', '30', '5', '87', '7']

core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '12', '81', '63', '55', '23', '16', '31', '22', '6', '44', '5', '7', '30', '27', '14', '10', '18', '87']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '12', '81', '63', '55', '23', '16', '31', '22', '6', '44', '5', '7', '30', '27', '14', '10', '18', '87']

core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '44', '23', '16', '63', '55', '6', '22', '14', '27', '10', '30', '18', '43', '87', '5', '12', '31']

core           INFO 	Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Emilia Romagna Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['81', '1', '63', '4', '14', '55', '23', '18', '6', '10', '16', '44', '12', '5', '43', '30', '27', '31', '87', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '1', '63', '4', '14', '55', '23', '18', '6', '10', '16', '44', '12', '5', '43', '30', '27', '31', '87', '22']

core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '16', '81', '1', '44', '6', '31', '30', '23', '55', '63', '87', '43', '5', '18', '27', '22', '12', '14', '10']

core           INFO 	Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Monaco Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '44', '1', '6', '14', '31', '30', '23', '55', '22', '27', '63', '12', '5', '87', '10', '18', '43']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '16', '81', '44', '1', '6', '14', '31', '30', '23', '55', '22', '27', '63', '12', '5', '87', '10', '18', '43']

core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']

INFO:fastf1.fastf1.core:Finished loading data for 19 drivers: ['81', '4', '16', '63', '27', '44', '6', '10', '14', '1', '30', '5', '22', '55', '43', '31', '87', '12', '23']

core           INFO 	Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Spanish Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '1', '63', '44', '12', '16', '10', '6', '14', '23', '5', '30', '18', '87', '27', '31', '55', '43', '22']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '4', '1', '63', '44', '12', '16', '10', '6', '14', '23', '5', '30', '18', '87', '27', '31', '55', '43', '22']

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']

core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Canadian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['63', '1', '81', '12', '44', '14', '4', '16', '6', '23', '22', '43', '27', '87', '31', '5', '55', '18', '30', '10']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '1', '81', '12', '44', '14', '4', '16', '6', '23', '22', '43', '27', '87', '31', '5', '55', '18', '30', '10']

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '44', '63', '30', '14', '5', '27', '31', '87', '6', '10', '18', '43', '22', '23', '1', '12', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '16', '44', '63', '30', '14', '5', '27', '31', '87', '6', '10', '18', '43', '22', '23', '1', '12', '55']

core           INFO 	Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Austrian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '16'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '16'

core        WARNING 	Fixed incorrect tyre stint information for driver '1'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '1'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Fixed incorrect tyre stint information for driver '12'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '12'

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '6'

core           INFO 	Finished loading data for 20 drivers: ['4', '16', '81', '44', '63', '30', '1', '5', '12', '10', '14', '23', '6', '43', '87', '18', '31', '22', '55', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '16', '81', '44', '63', '30', '1', '5', '12', '10', '14', '23', '6', '43', '87', '18', '31', '22', '55', '27']

core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 43)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 43)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']

core           INFO 	Loading data for British Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for British Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '44', '16', '12', '87', '14', '10', '55', '22', '6', '23', '31', '30', '5', '18', '27', '43']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '81', '4', '63', '44', '16', '12', '87', '14', '10', '55', '22', '6', '23', '31', '30', '5', '18', '27', '43']

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '81'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '81'

core        WARNING 	Fixed incorrect tyre stint information for driver '4'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '4'

core        WARNING 	Fixed incorrect tyre stint information for driver '16'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '16'

core        WARNING 	Fixed incorrect tyre stint information for driver '1'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '1'

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '63'

core        WARNING 	Fixed incorrect tyre stint information for driver '23'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '23'

core        WARNING 	Fixed incorrect tyre stint information for driver '44'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '44'

core        WARNING 	Fixed incorrect tyre stint information for driver '30'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '30'

core        WARNING 	Fixed incorrect tyre stint information for driver '5'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '5'

core        WARNING 	Fixed incorrect tyre stint information for driver '10'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '10'

core        WARNING 	Fixed incorrect tyre stint information for driver '87'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '87'

core        WARNING 	Fixed incorrect tyre stint information for driver '27'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '27'

core        WARNING 	Fixed incorrect tyre stint information for driver '22'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '22'

core        WARNING 	Fixed incorrect tyre stint information for driver '18'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '18'

core        WARNING 	Fixed incorrect tyre stint information for driver '31'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '31'

core        WARNING 	Fixed incorrect tyre stint information for driver '12'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '12'

core        WARNING 	Fixed incorrect tyre stint information for driver '14'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '14'

core        WARNING 	Fixed incorrect tyre stint information for driver '55'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '55'

core        WARNING 	Fixed incorrect tyre stint information for driver '43'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '43'

core        WARNING 	Fixed incorrect tyre stint information for driver '6'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '6'

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '16', '1', '63', '23', '44', '30', '5', '10', '87', '27', '22', '18', '31', '12', '14', '55', '43', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '4', '16', '1', '63', '23', '44', '30', '5', '10', '87', '27', '22', '18', '31', '12', '14', '55', '43', '6']

core           INFO 	Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Belgian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '16', '1', '23', '63', '22', '6', '30', '5', '31', '87', '10', '27', '55', '44', '43', '12', '14', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '16', '1', '23', '63', '22', '6', '30', '5', '31', '87', '10', '27', '55', '44', '43', '12', '14', '18']

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '14', '5', '18', '30', '1', '12', '6', '44', '27', '55', '23', '31', '22', '43', '10', '87']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '81', '63', '16', '14', '5', '18', '30', '1', '12', '6', '44', '27', '55', '23', '31', '22', '43', '10', '87']

core           INFO 	Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Hungarian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '63', '14', '18', '5', '1', '30', '6', '87', '44', '55', '43', '12', '22', '10', '31', '27', '23']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['16', '81', '4', '63', '14', '18', '5', '1', '30', '6', '87', '44', '55', '43', '12', '22', '10', '31', '27', '23']

core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['81', '1', '6', '63', '23', '87', '18', '14', '22', '31', '43', '30', '55', '27', '5', '12', '10', '4', '16', '44']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '1', '6', '63', '23', '87', '18', '14', '22', '31', '43', '30', '55', '27', '5', '12', '10', '4', '16', '44']

core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Dutch Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '1', '6', '63', '16', '44', '30', '55', '14', '12', '22', '5', '10', '23', '43', '27', '31', '87', '18']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '4', '1', '6', '63', '16', '44', '30', '55', '14', '12', '22', '5', '10', '23', '43', '27', '31', '87', '18']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '44', '23', '5', '12', '6', '55', '87', '22', '30', '31', '10', '43', '18', '14', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '44', '23', '5', '12', '6', '55', '87', '22', '30', '31', '10', '43', '18', '14', '27']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '63', '12', '5', '14', '22', '87', '27', '55', '23', '31', '6', '18', '43', '10', '30']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '63', '12', '5', '14', '22', '87', '27', '55', '23', '31', '6', '18', '43', '10', '30']

core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '55', '12', '30', '22', '4', '44', '16', '6', '5', '87', '23', '31', '14', '27', '18', '10', '43', '81']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '63', '55', '12', '30', '22', '4', '44', '16', '6', '5', '87', '23', '31', '14', '27', '18', '10', '43', '81']

core           INFO 	Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Azerbaijan Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '55', '30', '12', '63', '22', '4', '6', '81', '16', '14', '44', '5', '18', '87', '43', '27', '10', '23', '31']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '55', '30', '12', '63', '22', '4', '6', '81', '16', '14', '44', '5', '18', '87', '43', '27', '10', '23', '31']

core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['63', '1', '4', '81', '12', '16', '14', '44', '87', '55', '6', '22', '18', '23', '30', '43', '5', '31', '10', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '1', '4', '81', '12', '16', '14', '44', '87', '55', '6', '22', '18', '23', '30', '43', '5', '31', '10', '27']

core           INFO 	Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Singapore Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['63', '1', '81', '12', '4', '44', '16', '6', '87', '14', '27', '30', '22', '5', '18', '43', '31', '10', '23', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['63', '1', '81', '12', '4', '44', '16', '6', '87', '14', '27', '30', '22', '5', '18', '43', '31', '10', '23', '55']

core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '44', '81', '63', '22', '27', '87', '14', '30', '18', '12', '23', '31', '6', '43', '5', '10', '55']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '16', '44', '81', '63', '22', '27', '87', '14', '30', '18', '12', '23', '31', '6', '43', '5', '10', '55']

core           INFO 	Loading data for United States Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for United States Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '63', '44', '81', '12', '87', '55', '14', '27', '30', '22', '10', '43', '5', '31', '18', '23', '6']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '16', '63', '44', '81', '12', '87', '55', '14', '27', '30', '22', '10', '43', '5', '31', '18', '23', '6']

core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '16', '1', '87', '81', '12', '63', '44', '31', '5', '22', '23', '6', '18', '10', '43', '55', '14', '27', '30']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '16', '1', '87', '81', '12', '63', '44', '31', '5', '22', '23', '6', '18', '10', '43', '55', '14', '27', '30']

core           INFO 	Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Mexico City Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '16', '44', '63', '1', '12', '55', '81', '6', '87', '22', '31', '27', '14', '30', '5', '23', '10', '18', '43']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '16', '44', '63', '1', '12', '55', '81', '6', '87', '22', '31', '27', '14', '30', '5', '23', '10', '18', '43']

core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Driver 4 completed the race distance 00:00.010000 before the recorded end of the session.

WARNING:fastf1.fastf1.core:Driver 4 completed the race distance 00:00.010000 before the recorded end of the session.

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['4', '12', '1', '63', '81', '87', '30', '6', '27', '10', '23', '31', '55', '14', '43', '18', '22', '44', '16', '5']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '12', '1', '63', '81', '87', '30', '6', '27', '10', '23', '31', '55', '14', '43', '18', '22', '44', '16', '5']

core           INFO 	Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for São Paulo Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	No lap data for driver 5

WARNING:fastf1.fastf1.core:No lap data for driver 5

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 5)

WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 5)

core           INFO 	Finished loading data for 20 drivers: ['4', '12', '16', '81', '6', '63', '30', '87', '10', '27', '14', '23', '44', '18', '55', '1', '31', '43', '22', '5']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '12', '16', '81', '6', '63', '30', '87', '10', '27', '14', '23', '44', '18', '55', '1', '31', '43', '22', '5']

core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Las Vegas Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core        WARNING 	Fixed incorrect tyre stint information for driver '63'

WARNING:fastf1.fastf1.core:Fixed incorrect tyre stint information for driver '63'

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '63', '12', '16', '55', '6', '27', '44', '31', '87', '14', '22', '10', '30', '43', '23', '5', '18', '4', '81']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '63', '12', '16', '55', '6', '27', '44', '31', '87', '14', '22', '10', '30', '43', '23', '5', '18', '4', '81']

core           INFO 	Loading data for Las Vegas Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Las Vegas Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['4', '1', '55', '63', '81', '30', '14', '6', '16', '10', '27', '18', '31', '87', '43', '23', '12', '5', '22', '44']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['4', '1', '55', '63', '81', '30', '14', '6', '16', '10', '27', '18', '31', '87', '43', '23', '12', '5', '22', '44']

core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Qatar Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '55', '4', '12', '63', '14', '16', '30', '22', '23', '44', '5', '43', '31', '10', '18', '6', '87', '27']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '81', '55', '4', '12', '63', '14', '16', '30', '22', '23', '44', '5', '43', '31', '10', '18', '6', '87', '27']

core           INFO 	Loading data for Qatar Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Qatar Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['81', '4', '1', '63', '12', '6', '55', '14', '10', '16', '27', '30', '87', '5', '23', '22', '31', '44', '18', '43']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['81', '4', '1', '63', '12', '6', '55', '14', '10', '16', '27', '30', '87', '5', '23', '22', '31', '44', '18', '43']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

INFO:fastf1.fastf1.req:Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

req            INFO 	Using cached data for weather_data

INFO:fastf1.fastf1.req:Using cached data for weather_data

core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '81', '4', '16', '63', '14', '31', '44', '27', '18', '5', '87', '55', '22', '12', '23', '6', '30', '10', '43']

core           INFO 	Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

INFO:fastf1.fastf1.core:Loading data for Abu Dhabi Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

INFO:fastf1.fastf1.req:Using cached data for session_info

req            INFO 	Using cached data for driver_info

INFO:fastf1.fastf1.req:Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

INFO:fastf1.fastf1.req:Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

INFO:fastf1.fastf1.req:Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

INFO:fastf1.fastf1.req:Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

INFO:fastf1.fastf1.req:Using cached data for timing_app_data

core           INFO 	Processing timing data...

INFO:fastf1.fastf1.core:Processing timing data...

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '63', '16', '14', '5', '31', '6', '22', '87', '55', '30', '12', '18', '44', '23', '27', '10', '43']

INFO:fastf1.fastf1.core:Finished loading data for 20 drivers: ['1', '4', '81', '63', '16', '14', '5', '31', '6', '22', '87', '55', '30', '12', '18', '44', '23', '27', '10', '43']

1838 race-driver rows across 4 seasons

,year,round,driver,constructor,circuit,grid_position,quali_gap_to_pole_s,is_wet,points,finish_position
0,2022,1,LEC,Ferrari,Bahrain Grand Prix,1.0,0.000,False,26.0,1.0
1,2022,1,SAI,Ferrari,Bahrain Grand Prix,3.0,0.129,False,18.0,2.0
2,2022,1,HAM,Mercedes,Bahrain Grand Prix,5.0,0.490,False,15.0,3.0
3,2022,1,RUS,Mercedes,Bahrain Grand Prix,9.0,0.694,False,12.0,4.0
4,2022,1,MAG,Haas F1 Team,Bahrain Grand Prix,7.0,0.903,False,10.0,5.0

## 2. Run the pipeline (features → split → train → eval)

Temporal split, leakage-safe pre-race features, XGBoost with class weights.

In [4]:
result = run_pipeline(
    races,
    train_max_year=TRAIN_MAX_YEAR,
    val_year=VAL_YEAR,
    test_year=TEST_YEAR,
    version=MODEL_VERSION,
    fastf1_version=fastf1.__version__,
)
print(f"train rows: {result.n_train}  test rows: {result.n_test}")

train rows: 845  test rows: 467

## 3. Metrics vs. baseline ("podium = grid ≤ 3")

In [5]:
import pandas as pd

pd.DataFrame({"model": result.metrics, "baseline": result.baseline}).T[
    ["accuracy", "log_loss", "roc_auc"]
]

          accuracy  log_loss   roc_auc
model     0.865096  0.283088  0.934142
baseline  0.922912  1.065008  0.852215

In [6]:
from f1pred.evaluate import calibration_figure, confusion_figure
from f1pred.features import build_features
from f1pred.schema import FEATURE_NAMES
from f1pred.split import temporal_split
from f1pred.target import podium_label

# Rebuild the test fold to render the figures.
_feat = build_features(races)
_data = _feat.assign(
    podium=podium_label(races, position_col="finish_position").reindex(_feat.index)
)
_test = temporal_split(
    _data, train_max_year=TRAIN_MAX_YEAR, val_year=VAL_YEAR, test_year=TEST_YEAR
).test

confusion_figure(result.metrics)

In [7]:
calibration_figure(result.model, _test[list(FEATURE_NAMES)], _test["podium"])

## 4. SHAP — global + a single prediction

In [8]:
from f1pred.explain import importance_figure, one_prediction_figure, one_prediction_shap

importance_figure(result.importance)

In [9]:
one_prediction_figure(one_prediction_shap(result.model, _test[list(FEATURE_NAMES)]))

## 5. Publish the artifact + model card to S3

Needs AWS creds. Writes `models/<version>/model.json` + `model_card.md`.

In [10]:
import boto3

from f1pred.artifact import publish
from f1pred.layout import bucket_name

region = "eu-central-1"
account = boto3.client("sts").get_caller_identity()["Account"]
s3 = boto3.client("s3", region_name=region)

out = publish(
    result.model,
    result.card_text,
    version=MODEL_VERSION,
    s3_client=s3,
    bucket=bucket_name(account, region),
)
print("published", out)
print(result.card_text)

INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials

INFO:f1pred.artifact:uploaded model 0.1.0 to s3://f1-data-128663321407-eu-central-1/models/0.1.0/

published artifacts/0.1.0
# Model Card — Podium Predictor `0.1.0`

Binary XGBoost classifier: probability a driver finishes on the podium (P≤3).

## Data

- Source: FastF1 3.8.3.
- Seasons / split (temporal, no shuffle): train ≤2023, val 2024, test 2025.
- Rows: 845 train, 467 test.

## Features (pre-race only — no leakage)

- `grid_position` — mean|SHAP| 1.304
- `driver_form` — mean|SHAP| 1.155
- `quali_gap_to_pole_s` — mean|SHAP| 0.790
- `constructor_form` — mean|SHAP| 0.460
- `track_history` — mean|SHAP| 0.101
- `is_wet` — mean|SHAP| 0.026

## Metrics (test) vs. baseline "podium = grid ≤ 3"

| model | accuracy | log_loss | roc_auc |
| ----- | -------- | -------- | ------- |
| XGBoost | 0.865 | 0.283 | 0.934 |
| baseline | 0.923 | 1.065 | 0.852 |

## Limitations

Imbalanced target (~15% podium); FastF1 gaps dropped, not imputed; no live-session signal yet (Phase 5).

## Cost

Training is local + offline (FastF1 cache); the artifact is a few MB in S3 — ≈0 €
(Constitution IV).